name: union_admin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  one_context: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.1
  date_format: ^2.0.2
  logger: ^1.0.0
  intl: '0.17.0'
  http: ^0.13.5
  sprintf: ^7.0.0
  get_it: ^7.2.0
  styled_text: ^7.0.0
  indexed: ^0.0.8
  flutter_dotenv: ^5.0.2
  dotted_border: ^2.0.0+3
  dropdown_button2: ^2.0.0
  auto_size_text: ^3.0.0
  gradient_progress_indicator: ^1.0.0+5
  cupertino_icons: ^1.0.2
  painter: ^2.0.0
  hovering: ^1.0.4
  defer_pointer: ^0.0.2
  kpostal_web: ^0.0.2
  file_picker: ^6.1.1
  dio: ^5.4.0
  url_launcher: ^6.2.4
  pdf: ^3.10.7
  printing: ^5.11.1
  open_file: ^3.3.2
  path_provider: ^2.1.2
  http_parser: ^4.0.0
  croppy: ^1.1.4
  flutter_inappwebview: ^6.0.0
  uuid: ^3.0.6
  webviewx_plus: ^0.3.3
  number_text_input_formatter: ^1.0.0
  circular_countdown_timer: ^0.2.3
  web_socket_client: ^0.1.0
  # excel: ^4.0.3
 
    

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - .env
   - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
    # - family: Montserrat
    #   fonts:
    #     - asset: assets/fonts/Montserrat-Thin.ttf
    #       weight: 100
    #     - asset: assets/fonts/Montserrat-ExtraLight.ttf
    #       weight: 200
    #     - asset: assets/fonts/Montserrat-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/Montserrat-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Montserrat-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Montserrat-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Montserrat-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/Montserrat-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/Montserrat-Black.ttf
    #       weight: 900
       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
