//보드 프론트 작업용 임시1
var getDummyData1 = {
  "IsSuccess": true,
  "Data": {
    "List": [
      {
        "myPageSeq": 1,
        "myPageType": '일반',
        "myPageTitle": '대학생들에게 장학증서 준 이부진, 옷 가격 10만원 좀 넘네',
        "myPageStatusCheckYN": 'N',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 2,
        "myPageType": '일반',
        "myPageTitle": '윤석민 태영 회장, 태영건설 아닌 티와이홀딩스에 416억 투입',
        "myPageStatusCheckYN": 'Y',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 3,
        "myPageType": '딜',
        "myPageTitle": '금호석화, 금호피앤비화학 신임 대표에 이정복 부사장 선임23분전',
        "myPageStatusCheckYN": 'N',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 4,
        "myPageType": '딜',
        "myPageTitle": '대통령이 지원하겠다더니...양자 국제공동연구센터 예산 25% 잘랐다',
        "myPageStatusCheckYN": 'Y',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 5,
        "myPageType": '딜',
        "myPageTitle": '“계약 환불해도 손해 없어요”… 미분양 늘자 고개 든 ‘확정금’ 분양',
        "myPageStatusCheckYN": 'Y',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 6,
        "myPageType": '일반',
        "myPageTitle": '홍해 위기로 유럽행 물류비 급증… 한달 새 3배 올라',
        "myPageStatusCheckYN": 'N',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 7,
        "myPageType": '일반',
        "myPageTitle": '대통령이 지원하겠다더니...양자 국제공동연구센터 예산 25% 잘랐다',
        "myPageStatusCheckYN": 'Y',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 8,
        "myPageType": '딜',
        "myPageTitle": '블랙핑크 계약에 휘청이는 YG엔터... “돈 잘 벌 때 단일 의존도 해소했어야”',
        "myPageStatusCheckYN": 'N',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 9,
        "myPageType": '딜',
        "myPageTitle": '“여보, 빚부터 갚자”…가계대출 증가세 ‘주춤’',
        "myPageStatusCheckYN": 'Y',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 10,
        "myPageType": '딜',
        "myPageTitle": "[단독] 샤넬, 화장품부터 올린다…'넘버5' 30만원 턱밑",
        "myPageStatusCheckYN": 'Y',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
      {
        "myPageSeq": 11,
        "myPageType": '딜',
        "myPageTitle": "[단독] 샤넬, 화장품부터 올린다…'넘버5' 30만원 턱밑",
        "myPageStatusCheckYN": 'Y',
        "myPageDateTime": '20241112200000',
        "page": 0,
        "useYN": 'Y',
      },
    ],
  },
  "ErrorMsg": null,
};

//보드 프론트 작업용 임시2
var getDealData = {
  "IsSuccess": true,
  "Data": {
    "List": [
      {
        "myDealSeq": 1,
        "myDealType": '토지',
        "myDealTitle": '부산시 해운대구 부부동 34-2 보보빌라',
        "myDealImg": 'assets/img/img_mydeal_dummy_01.png',
        "myDealPjtList": ['코리빙', '강남', '서초', '키움', '마스턴'],
        "myDealPjtColorList": ['1', '2', '3', '4', '5'],
        "myDealDesc": '인사동 빌라 리모델링',
        "myDealStatus1": '독점등록',
        "myDealStatus2": '보류',
        "myDealStatus3": '사업모델링(수익성검토)',
        "myDealPrice": 1558,
        "myDealTotalFloorArea": 495.868,
        "myDealLandArea": 495.868,
        "myDealLotInfoList": [
          ['광사동', 305, 92.2, '3종 일반주거지역', 8320000, 2537600000, '포함', 3537600000],
          ['고읍동', 305, 92.2, '3종 일반주거지역', 8320000, 2537600000, '포함', 3537600000],
        ],
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "myDealSeq": 2,
        "myDealType": '건물',
        "myDealTitle": '경기도 안산시 안산구 안산동 1234-2 스와빌딩',
        "myDealImg": 'assets/img/img_mydeal_dummy_02.png',
        "myDealPjtList": ['서초'],
        "myDealPjtColorList": ['1'],
        "myDealDesc": '인사동 빌라 리모델링',
        "myDealStatus1": '일반등록',
        "myDealStatus2": '거래완료',
        "myDealStatus3": '사업성검토중',
        "myDealPrice": 1558,
        "myDealTotalFloorArea": 495.868,
        "myDealLandArea": 495.868,
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "myDealSeq": 3,
        "myDealType": '건물',
        "myDealTitle": '서울시 종로구 인사동 34-2 보보빌딩',
        "myDealImg": 'assets/img/img_mydeal_dummy_03.png',
        "myDealPjtList": [],
        "myDealPjtColorList": [],
        "myDealDesc": '인사동 빌라 리모델링',
        "myDealStatus1": '일반등록',
        "myDealStatus2": '거래중',
        "myDealStatus3": '검토중',
        "myDealPrice": 1558,
        "myDealTotalFloorArea": 495.868,
        "myDealLandArea": 495.868,
        "createDateTime": '20241112200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
    ],
  },
  "ErrorMsg": null,
};

//보드 프론트 작업용 임시3(메모)
var getMemoData = {
  "IsSuccess": true,
  "Data": {
    "List": [
      {
        "myDealDetailSeq": 1,
        "myDealSeq": 1,
        "myDealDetailCompany": '이클립스 토지중계 사무소',
        "myDealDetailWriter": '윤이온(yoonion)',
        "myDealDetailMemo": '네 수정 끝났고 2 → 1.5로 변경했습니다. 확인 바랍니다.',
        "myDealDetailFile": '',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "myDealDetailSeq": 2,
        "myDealSeq": 1,
        "myDealDetailCompany": '',
        "myDealDetailWriter": '관리자',
        "myDealDetailMemo": '안녕하세요, 지난 달 30일에 남겨주신 내용대로 수정이 다 되었다는 말씀이시죠?',
        "myDealDetailFile": '',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "myDealDetailSeq": 3,
        "myDealSeq": 1,
        "myDealDetailCompany": '',
        "myDealDetailWriter": 'System',
        "myDealDetailMemo": '딜 정보가 수정되었습니다.',
        "myDealDetailFile": '',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "myDealDetailSeq": 4,
        "myDealSeq": 2,
        "myDealDetailCompany": '',
        "myDealDetailWriter": '관리자',
        "myDealDetailMemo": '안녕하세요, 지난 달 30일에 남겨주신 내용대로 수정이 다 되었다는 말씀이시죠?',
        "myDealDetailFile": '',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "myDealDetailSeq": 5,
        "myDealSeq": 1,
        "myDealDetailCompany": '이클립스 토지중계 사무소',
        "myDealDetailWriter": '윤이온(yoonion)',
        "myDealDetailMemo": '건물주가 우선은 매매 계약을 하고 싶다고 합니다. 어떻게 변경하면 될까요? 이 딜을 삭제 하고',
        "myDealDetailFile": '',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "myDealDetailSeq": 6,
        "myDealSeq": 1,
        "myDealDetailCompany": '',
        "myDealDetailWriter": '관리자',
        "myDealDetailMemo": '안녕하세요, 이번에 가서 찍은 사진을 첨부합니다. 날씨가 좋아서 외관 사진을 여러장 찍었는데 그 중 제일 잘 나온 것으로 올립니다.',
        "myDealDetailFile": 'building111 .jpg',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
    ],
  },
  "ErrorMsg": null,
};

//보드 프론트 작업용 임시(공지사항)
var getFaqData = {
  "IsSuccess": true,
  "Data": {
    "List": [
      {
        "faqSeq": 1,
        "faqCategory": '회원가입',
        "faqQuestion": '가입 신청은 뭔가요?',
        "faqAnswer": '딜스테이션의 서비스 품질 향상을 위해 회원 가입은 신청 심사 후 승인하는 방식으로 운영되고 있습니다',
        "faqAnswerDesc":
            '결과가 전송되지 않는다면 혹시 휴대전화번호를 오기재 하시지 않았는지 확인 부탁드립니다. 메인 화면에서 로그인을 선택하신 후 가입 시 작성한 아이디와 비밀번호를 입력하면 신청 내역을 확인하실 수 있습니다.',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
      {
        "faqSeq": 2,
        "faqCategory": '회원가입',
        "faqQuestion": '가입 신청은 뭔가요?',
        "faqAnswer": '딜스테이션의 서비스 품질 향상을 위해 회원 가입은 신청 심사 후 승인하는 방식으로 운영되고 있습니다',
        "faqAnswerDesc":
            '결과가 전송되지 않는다면 혹시 휴대전화번호를 오기재 하시지 않았는지 확인 부탁드립니다. 메인 화면에서 로그인을 선택하신 후 가입 시 작성한 아이디와 비밀번호를 입력하면 신청 내역을 확인하실 수 있습니다.',
        "createDateTime": '20230712200000',
        "updateDateTime": '20241112200000',
        "useYN": 'Y',
        "page": 0,
      },
    ],
  },
  "ErrorMsg": null,
};
